#!/bin/sh

#
# Globals
#
master="gaia-dns"
slaves="nyx-dns shu-dns"
config="/usr/local/etc/nsd"
nsdcmd="service nsd reload"

#
# Optional
#
sshkey="~/.ssh/ns_ed255519"
EDITOR="nvim"

progname=${0##*/}

#
# Functions
#
usage ()
{
	cat <<EOF
usage: $progname [options] ...

EOF
	exit 1
}

error ()
{
	echo "$progname: $*" >&2
	exit 1
}

gen_tmp ()
{
	tmpfile="/tmp/$progname"."$(awk 'BEGIN {srand();printf "%d\n", rand() * 10^10}')"
}

connect_master ()
{
	if [ $sshkey ]
	then
		sshoptions=" -i $sshkey"
	fi
	gen_tmp
	masterssh="ssh $sshoptions -o ControlPath=$tmpfile"
	masterscp="scp $sshoptions -o ControlPath=$tmpfile"

	trap "cleanup" INT TERM HUP EXIT
	if ! $masterssh -MNf $master
	then
		error "SSH connection to $master failed"
	fi
}

connect_slave ()
{
	gen_tmp
	slavessh="ssh $sshoptions -o ControlPath=$tmpfile"
	slavescp="scp $sshoptions -o ControlPath=$tmpfile"

	if ! $slavessh -MNf $slave
	then
		error "SSH connection to $slave failed"
	fi
}

disconnect_slave ()
{
	$slavessh -O exit $slave 2> /dev/null
}

list_zones ()
{
	if ! $masterssh $master "ls $config"
	then
		error "SSH connection to $master failed"
	fi
}

get_zone ()
{
	gen_tmp
	zonefile=$tmpfile
	if ! $masterscp $master:$config/$zone $zonefile
	then
		error "could not download from $master"
	fi
}

edit_zone ()
{
	if ! $EDITOR $zonefile
	then
		error "could not edit $zonefile"
	fi
}

upload_zone ()
{
	echo "updating $master..."
	$masterscp $zonefile $master:$config/$zone &&
	$masterssh $master $nsdcmd

	for slave in $slaves
	do
		echo "updating $slave..."
		connect_slave
		$slavescp $zonefile $slave:$config/$zone &&
		$slavessh $slave $nsdcmd
		disconnect_slave
	done
}

delete_zone ()
{
	$masterssh $master "rm $config/$zone"
	for slave in $slaves
	do
		connect_slave
		$slavessh $slave "rm $config/$zone"
		disconnect_slave
	done
}

cleanup ()
{
	$masterssh -O exit $master 2> /dev/null
	$slavessh -O exit $slave 2> /dev/null
	rm $zonefile 2> /dev/null
}

interactive_mode ()
{
	list_zones
	echo "Enter e for edit, n for new and d for delete"
	read ch
	case $ch in
	e)
		echo "Enter a file"
		read zone
		get_zone
		edit_zone
		upload_zone
		;;
	n)
		echo "File name"
		read zone
		gen_tmp
		zonefile=$tmpfile
		edit_zone
		upload_zone
		;;
	d)
		echo "File name"
		read zone
		echo "Are you sure to delete $zone? (y/N)"
		read ch
		case $ch in
		y|Y|yes|YES)
			delete_zone
			;;
		esac
		;;
	esac
}

#
# Main
#
main ()
{
	connect_master
	if [ $# -eq 0 ]
	then
		interactive_mode
	else
	fi
	exit 0
}

main "$@"
